name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - uses: actions/checkout@v2
      
      - run: npm install -g yarn
      - run: yarn install --frozen-lockfile
      - run: yarn run build

      - name: rsync deployments
        uses: burnett01/rsync-deployments@5.1
        with:
          switches: -avzr --delete
          path: ./*
          remote_path: /var/www/api/
          remote_host: 192.241.154.174
          remote_user: root
          remote_key: "${{ secrets.SSH_PRIVATE_KEY }}"
